### ISSUE TITLE
Chrome stuck on v67?

### ISSUE THREAD

**Issue by PacoBell** [appget/appget.packages#4214]
How can you claim "AppGet’s applications are validated hourly to make sure all information is accurate. This includes checking for **newer versions**, scanning for viruses, and making sure download links are still valid." when Chrome apparently hasn't been updated to the current v77? That's a whole 10 versions behind! Why should I trust any of the other packages in your list are treated any better?

**Comment by kayone** [comment]
First of all, I just checked and it seems like there is a problem with chrome and the manifest hasn't been updated in a few days, _however_ if you actually install the package it'll install the latest version since the installer URL is correct and it'll install v77.

We do our best effort to keep the library updated and as you can see https://github.com/appget/appget.packages/commits/master most of it is automated.

every piece of software is gonna have bugs, or cases where things fall through the cracks, we try out best but we don't claim that it's gonna be perfect. This is the case with _every_ piece of software, and if anyone tells you otherwise they are either lying or delusional.

>  Why should I trust any of the other packages in your list are treated any better?
You don't have to. feel free to stop using appget anytime you like.
